apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.9.6
  - root-apps/argocd.yaml
  - root-apps/dev-apps.yaml
  - root-apps/prod-apps.yaml
